CREATE TABLE IF NOT EXISTS `charity_partbs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `regno` varchar(14) CHARACTER SET latin1 NOT NULL DEFAULT '0',
  `artype` char(4) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `fystart` datetime DEFAULT NULL,
  `fyend` datetime DEFAULT NULL,
  `inc_leg` bigint(20) DEFAULT NULL,
  `inc_end` bigint(20) DEFAULT NULL,
  `inc_vol` bigint(20) DEFAULT NULL,
  `inc_fr` bigint(20) DEFAULT NULL,
  `inc_char` bigint(20) DEFAULT NULL,
  `inc_invest` bigint(20) DEFAULT NULL,
  `inc_other` bigint(20) DEFAULT NULL,
  `inc_total` bigint(20) DEFAULT NULL,
  `invest_gain` bigint(20) DEFAULT NULL,
  `asset_gain` bigint(20) DEFAULT NULL,
  `pension_gain` bigint(20) DEFAULT NULL,
  `exp_vol` bigint(20) DEFAULT NULL,
  `exp_trade` bigint(20) DEFAULT NULL,
  `exp_invest` bigint(20) DEFAULT NULL,
  `exp_grant` bigint(20) DEFAULT NULL,
  `exp_charble` bigint(20) DEFAULT NULL,
  `exp_gov` bigint(20) DEFAULT NULL,
  `exp_other` bigint(20) DEFAULT NULL,
  `exp_total` bigint(20) DEFAULT NULL,
  `exp_support` bigint(20) DEFAULT NULL,
  `exp_dep` bigint(20) DEFAULT NULL,
  `reserves` bigint(20) DEFAULT NULL,
  `asset_open` bigint(20) DEFAULT NULL,
  `asset_close` bigint(20) DEFAULT NULL,
  `fixed_assets` bigint(20) DEFAULT NULL,
  `open_assets` bigint(20) DEFAULT NULL,
  `invest_assets` bigint(20) DEFAULT NULL,
  `cash_assets` bigint(20) DEFAULT NULL,
  `current_assets` bigint(20) DEFAULT NULL,
  `credit_1` bigint(20) DEFAULT NULL,
  `credit_long` bigint(20) DEFAULT NULL,
  `pension_assets` bigint(20) DEFAULT NULL,
  `total_assets` bigint(20) DEFAULT NULL,
  `funds_end` bigint(20) DEFAULT NULL,
  `funds_restrict` bigint(20) DEFAULT NULL,
  `funds_unrestrict` bigint(20) DEFAULT NULL,
  `funds_total` bigint(20) DEFAULT NULL,
  `employees` int(11) DEFAULT NULL,
  `volunteers` int(11) DEFAULT NULL,
  `cons_acc` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `charity_acc` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);