# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbcc8258895d4d3abb8d276dc4e6c7b465ea665b3f658518a6d5a5357a4a7211c5d77398fa15ec78f02c575622a0d51d2e96b74f179943cd284045010f06d1f8

test:
  secret_key_base: f1064c205019615f942a16dde9596d98210b787be971a2bfe8f83202def9b1f101afb76e2ecbae1059aabf5a6d5ad1fd2e013b3b9f8ae9991857883742a7f0e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
